#!/usr/bin/env bash

if [ -z "$SAGE_LOCAL" ]; then
    echo >&2 "SAGE_LOCAL undefined ... exiting"
    echo >&2 "Maybe run 'sage --sh'?"
    exit 1
fi

cd src

rm $SAGE_LOCAL/lib/python/libstamina.so
rm -rf $SAGE_LOCAL/lib/python/site-packages/stamina*

python setup.py install
cp libstamina.so $SAGE_LOCAL/lib/python/
